export enum Method {
  NEWTONINTERPOLATION = 'NEWTON INTERPOLATION',
  TRIGONOMETRICINTERPOLATION = 'TRIGONOMETRIC INTERPOLATION',
  SPLINEINTERPOLATION = '3rd ORDER SPLINE INTERPOLATION',
  POLYNOMIALAPPROXIMATION = 'POLYNOMIAL APPROXIMATION',
  TRIGONOMETRICAPPROXIMATION = 'TRIGONOMETRIC APPROXIMATION'
}
